# Autogenerated wrapper script for FPLLL_jll for aarch64-apple-darwin
export libfplll, libfplll_julia_shim

using GMP_jll
using MPFR_jll
JLLWrappers.@generate_wrapper_header("FPLLL")
JLLWrappers.@declare_library_product(libfplll, "@rpath/libfplll.9.dylib")
JLLWrappers.@declare_library_product(libfplll_julia_shim, "@rpath/libfplll_julia_shim.dylib")
function __init__()
    JLLWrappers.@generate_init_header(GMP_jll, MPFR_jll)
    JLLWrappers.@init_library_product(
        libfplll,
        "lib/libfplll.9.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libfplll_julia_shim,
        "lib/libfplll_julia_shim.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
