# Autogenerated wrapper script for FPLLL_jll for x86_64-linux-gnu-cxx11
export libfplll, libfplll_julia_shim

using GMP_jll
using MPFR_jll
JLLWrappers.@generate_wrapper_header("FPLLL")
JLLWrappers.@declare_library_product(libfplll, "libfplll.so.9")
JLLWrappers.@declare_library_product(libfplll_julia_shim, "libfplll_julia_shim.so")
function __init__()
    JLLWrappers.@generate_init_header(GMP_jll, MPFR_jll)
    JLLWrappers.@init_library_product(
        libfplll,
        "lib/libfplll.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libfplll_julia_shim,
        "lib/libfplll_julia_shim.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
